# Generated by Django 4.2.11 on 2024-03-22 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prod_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('rented_by', models.CharField(default='Not yet')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.FileField(upload_to='products/')),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField()),
                ('rent_type', models.CharField(choices=[('/hour', '/hour'), ('/day', '/day'), ('/week', '/week'), ('/month', '/month'), ('/year', '/year')], default='/hour', max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_to', models.CharField(max_length=2)),
                ('msg_from', models.CharField(max_length=2)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('msg_type', models.CharField(max_length=1)),
                ('message', models.CharField(max_length=200)),
                ('chat_prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
