# Generated by Django 4.2.11 on 2024-03-19 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prod_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.FileField(upload_to='products/')),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField()),
                ('rent_type', models.CharField(choices=[('/hour', '/hour'), ('/day', '/day'), ('/week', '/week'), ('/month', '/month'), ('/year', '/year')], default='/hour', max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
