# Generated by Django 4.2.11 on 2024-03-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rent_type',
            field=models.CharField(choices=[('/hour', '/hour'), ('/day', '/day'), ('/week', '/week'), ('/month', '/month'), ('/year', '/year')], default='/hour', max_length=10),
        ),
    ]
