# Generated by Django 4.2.11 on 2024-03-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_buyer_id_chatmessages_msg_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rented_by',
            field=models.CharField(default='Not yet'),
        ),
    ]
