# Generated by Django 4.2.11 on 2024-03-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
